name: Rodar apenas aos sábados
on:
  schedule:
    - cron: '0 0 * * *'


jobs:
  saturday:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar se é sábado
        run: |
          dow=$(date -u +"%u")
          if [ "$dow" -eq 6 ]; then
            echo "Hoje é sábado (UTC). Continuando..."
          else
            echo "Não é sábado. Encerrando." && exit 0
          fi