name: Contar HTML
on: [push]


jobs:
  count-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Contar arquivos HTML
        run: |
          html_count=$(ls -1 *.html 2>/dev/null | wc -l)
          echo "Total de arquivos HTML: $html_count"